require-stack-version: ">= 1.6"

resolver: lts-14.27

packages:
- .
- jni
- jvm
- jvm-batching
- jvm-streaming
- examples/classpath

extra-deps:
# Pinning Cabal and parsec here prevents stack from building a newer
# cabal than the one delivered with ghc.
- Cabal-2.4.0.1
- parsec-3.1.13.0

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
