require-stack-version: ">= 1.6"

resolver: lts-13.20

packages:
- .
- jni
- jvm
- jvm-batching
- jvm-streaming
- examples/classpath

extra-deps:
- Cabal-2.4.0.1 # Pinning Cabal here prevents stack from
                # building a newer cabal than the one delivered
                # with ghc.

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
