require-stack-version: ">= 1.6"

resolver: lts-13.20

packages:
- .
- jni
- jvm
- jvm-batching
- jvm-streaming
- examples/classpath

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
