version: 2
jobs:
  build:
    docker:
      - image: nixos/nix
    working_directory: ~/inline-java
    steps:
      - checkout
      - run:
          name: Install Stack
          command: |
            apk update --no-progress && apk --no-progress add ca-certificates bash
            nix-env -f nixpkgs.nix -iA stack
      - run:
          name: Compute cache key
          command: |
              (echo shell.nix; echo nixpkgs.nix; find . -name "*.cabal" -o -name "stack.yaml" -type f) | sort | xargs cat > /tmp/stack-deps
      - restore_cache:
          keys:
            - inline-java-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
            - inline-java-stack-dependencies-{{ arch }}-
      - run:
          name: Build dependencies
          command: |
            stack --no-terminal --nix build --only-snapshot --prefetch --test --bench
      - save_cache:
          key: inline-java-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
          paths:
            - ~/.stack
      - run:
          name: Build project
          command: stack --nix --no-terminal build --pedantic --test --bench --no-run-tests --no-run-benchmarks
      - run:
          name: Test
          command: stack --nix --no-terminal test
