steps:
  - label: "Run tests (Bazel)"
    command: |
      . /var/lib/buildkite-agent/.nix-profile/etc/profile.d/nix.sh
      echo "build --host_platform=@rules_haskell//haskell/platforms:linux_x86_64_nixpkgs" > .bazelrc.local
      nix-shell --pure --run 'bazel build //...'
    timeout: 30
  - label: "Run tests (Stack)"
    command: |
      . /var/lib/buildkite-agent/.nix-profile/etc/profile.d/nix.sh
      nix-shell --pure --run 'stack --nix build --pedantic --test --bench --no-run-benchmarks'
    timeout: 30
